language: generic

sudo: required

dist: trusty

services:
  - docker

before_install:
  - sudo pip install --user codecov

install:
  - docker pull lamtev/java

matrix:
  include:
    - env: HW="matrix"
    - env: HW="pokemons"
    - env: HW="lfu"

script:
  - docker run -v $TRAVIS_BUILD_DIR:/ajc lamtev/java /bin/bash -c " cd ajc/${HW} && cloc * && gradle build "
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - if [ ${HW} != "lfu" ]; then sudo mv ${TRAVIS_BUILD_DIR}/${HW}/cli/build/libs/cli-1.0.jar ${TRAVIS_BUILD_DIR}/${HW}/cli/build/libs/${HW}.jar && sudo chmod 777 ${TRAVIS_BUILD_DIR}/${HW}/cli/build/libs/${HW}.jar; fi
  
deploy:
  provider: releases
  api_key: "$GITHUB_DEPLOY_TOKEN"
  file: 
    - ${TRAVIS_BUILD_DIR}/${HW}/cli/build/libs/${HW}.jar
  skip_cleanup: true
  on:
    tags: true
