language: generic

sudo: required

dist: trusty

services:
  - docker

before_install:
  - sudo pip install --user codecov

install:
  - docker pull lamtev/java

matrix:
  include:
    - env: EPISODE="matrix"
    - env: EPISODE="pokemons_fighting"

script:
  - docker run -v $TRAVIS_BUILD_DIR:/ajc lamtev/java /bin/bash -c " cd ajc/${EPISODE} && cloc * && gradle build "
  - sudo mv ${TRAVIS_BUILD_DIR}/${EPISODE}/cli/build/libs/cli-1.0.jar ${TRAVIS_BUILD_DIR}/${EPISODE}/cli/build/libs/MatrixMultiplication.jar
  - sudo chmod 777 ${TRAVIS_BUILD_DIR}/${EPISODE}/cli/build/libs/MatrixMultiplication.jar
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
deploy:
  provider: releases
  api_key: "$GITHUB_DEPLOY_TOKEN"
  file: 
    - ${TRAVIS_BUILD_DIR}/${EPISODE}/cli/build/libs/MatrixMultiplication.jar
  skip_cleanup: true
  on:
    tags: true
